### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by lijiazhen1994** [yscacaca/HHAR-Data-Process#2]
I see the code on your github and would like to ask that **# the line 252 in the file of  sep_HHAR_data.py.**         XY = np.hstack (X, Y) When I run the code ,it will appear      "ValueError: all the input arrays must have same number of dimensions",  but X.shape is (0,) and Y.shape is (0,).               Do you know how to solve the problem? Thank you.
`X (0,) float64 Y (0,) float64 maskX (0,) float64
evalX (0,) float64 evalY (0,) float64 evalMaskX (0,) float64
Traceback (most recent call last):
  File "C:/Users/ljz/PycharmProjects/HHAR-Data-Process-master/sep_HHAR_data.py", line 252, in <module>
    XY = np.hstack((X, Y))
  File "C:\Users\ljz\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions` @yscacaca

**Comment by yscacaca** [comment]
Have you first run `python dataAli-sameUserDevice.py` and `python pairDataFile.py` with the downloaded dataset? It seems that the code didn't receive any inputs.

**Comment by lijiazhen1994** [comment]
![qq 20170715110624](https://user-images.githubusercontent.com/18414032/28236063-99f8717e-694e-11e7-9419-61d5534d3585.png)
Hello , Thank you very much for your reply.     I run  python dataAli-sameUserDevice.py and python pairDataFile.py with the downloaded dataset.       **# but There is no file under the folder "Dataset_AccGry_SourceDevice-Creation_Time-avgTime" and "Dataset_Alg_SourceDevic**e". I am looking forword to your reply. @yscacaca

**Comment by yscacaca** [comment]
Could you please show me the output information while running the code dataAli-sameUserDevice.py?

**Comment by lijiazhen1994** [comment]
![2](https://user-images.githubusercontent.com/18414032/28236915-8e2872c4-6965-11e7-98be-523ea0a59d0b.png)

**Comment by yscacaca** [comment]
Could you run the code python2.7? dataAli-sameUserDevice.py should output the progress during file processing. The output information indicates that no csv files are found in the 'Activity recognition exp' folder.

**Comment by lijiazhen1994** [comment]
Thank you! I solved the problem with python 2.7 and maked sure that csv files are found in the 'Activity recognition exp' folder.

**Comment by sinhaaditi** [comment]
Hi I have just one file with type walk for user h for nexus4_1.When I run the sep_HHAR_data.py .It gives me a error such as .
![screen shot 2018-07-25 at 7 51 48 pm](https://user-images.githubusercontent.com/22542156/43233501-3cd4bff2-9044-11e8-936e-7fc2b37e23b9.png)
My file is placed in the current folder .Can anyone explain me the error.

**Comment by ganyeshprasanna** [comment]
Hi @sinhaaditi , 
I think that it is not able to segment the data. You can see that the shape of X is 0,2400. This means that it has not values in it. That is why hstack is failing.
