### ISSUE TITLE
is the timestamp of csv file in a standard timestamp format?

### ISSUE THREAD

**Issue by kaixinbuyu** [yscacaca/HHAR-Data-Process#3]
1.The code is using "Creation_Time"(1424696631913248572),and discard "Arrival_Time" field.

_head -2 Phones_accelerometer.csv 
Index,Arrival_Time,Creation_Time,x,y,z,User,Model,Device,gt
0,1424696633908,**1424696631913248572**,-5.958191,0.6880646,8.135345,a,nexus4,nexus4_1,stand_

and **1424696631913248572** is a timestamp with ns(10-9 second) precision.

2.But there are other Creation_Time not in ns timestamp format:

 _tail -2  Phones_accelerometer.csv 
129051,1424778553386,**92263852409000**,1.53227,0.0,9.959755,i,samsungold,samsungold_2,bike
129052,1424778553395,**92263861839000**,1.379043,0.0,9.959755,i,samsungold,samsungold_2,bike_

**92263861839000** it seems a second in your code:
_curSaveElem['Time'] = 0.5*(curTime1 + curTime2)
curTime = curElem['Time']_

so I'm confused 
(1).what's the unit of "Creation_Time"?
(2).How to use "Creation_Time" as a standard timestamp?
why for this is because I want to use a timeseries database to preprocess these datas.

**Comment by kaixinbuyu** [comment]
there are [19, 14, 15, 13] 4 lengthes of "Creation_Time".

>>(1) process file:/home/go/store/workspace/archives/datas/activity_reg/Activity_recognition_exp/Phones_gyroscope.csv
ts: [19, 14, 15, 13]
>>(2) process file:/home/go/store/workspace/archives/datas/activity_reg/Activity_recognition_exp/Phones_accelerometer.csv
ts: [19, 14, 15, 13, 12]
>>(3) process file:/home/go/store/workspace/archives/datas/activity_reg/Activity_recognition_exp/Watch_accelerometer.csv
ts: [14, 13, 15, 12]
>>(4) process file:/home/go/store/workspace/archives/datas/activity_reg/Activity_recognition_exp/Watch_gyroscope.csv
ts: [14, 13, 15, 12]

**Comment by yscacaca** [comment]
The "starting point" of the Creation_Time seem to be different for different devices, but their difference are the same for each device. If you want to process the data with a database, you can use the arrival_time, which is in the NTP format. Since both "arrival_time" and "creation_time" cannot act as the "true" timestamp, choose either one should be fine.
