### ISSUE TITLE
Doubts on the pre-processing in a real-world scenario

### ISSUE THREAD

**Issue by DavideBuffelli** [yscacaca/HHAR-Data-Process#7]
Hi, thank you for sharing your code. I've read your article and I looked at your code for the data pre-processing but I have some doubts on how to do it in a real-world scenario. I thought about the following procedure:

1 - Collect a 5 second sample of measurements from the sensors.

2 - Divide it into 20 intervals of length 0.25 seconds.

3 - Take 10 random measurements from each time interval of length 0.25 seconds, and apply the Fourier Transform to each of them. [Each measurement is a vector of length 3 of real values, so we have that the the FFT function will return a complex-valued vector(Spectral Sample) of length 3. This complex values are divided into magnitude and phase pairs and this gives us 6 real values for each measurement. So, considering that we have two sensors, this gives us 10 x 6 x 2 = 120 values for spectral sample.]

4 - Save everything in a tensor of the appropriate size.

5 - Give it as input to the DeepSense framework.

Could you please tell me if my approach is correct(especially in the third step)?

**Comment by hhlgithub** [comment]
I am also reading this paper and related codes. But I do not think it takes 10 random measurements from each time interval of length 0.25 seconds.  The dimension of the input  is **wide * inputFeature** **(20 * 120)** in the code. the wide is 20 as described in your step 2 , and the inputFeature is  **sepcturalSamples * 6 * 2** as described in your step 3 **(10 * 6 * 2=120)**.

**Comment by DavideBuffelli** [comment]
I don't understand how to choose the 10 measurements for each 0.25 seconds interval. In this pre-processing code it seems like they interpolate the measurements of the interval and then pick 10 (random?) points. In the paper these things are not specified.

**Comment by hhlgithub** [comment]
I also do not understand it. Maybe it is related to the sampling rate of a sensor. For example, if the sampling rate is 100 Hz, Theoretically it indicates that there are exactly 100 samples in one second. But it may be less than 100 samples because of some precision problem of the sensor or other reasons in reality. So it need to interpolation.

**Comment by royanimal** [comment]
> Hi, thank you for sharing your code. I've read your article and I looked at your code for the data pre-processing but I have some doubts on how to do it in a real-world scenario. I thought about the following procedure:
> 
> 1 - Collect a 5 second sample of measurements from the sensors.
> 
> 2 - Divide it into 20 intervals of length 0.25 seconds.
> 
> 3 - Take 10 random measurements from each time interval of length 0.25 seconds, and apply the Fourier Transform to each of them. [Each measurement is a vector of length 3 of real values, so we have that the the FFT function will return a complex-valued vector(Spectral Sample) of length 3. This complex values are divided into magnitude and phase pairs and this gives us 6 real values for each measurement. So, considering that we have two sensors, this gives us 10 x 6 x 2 = 120 values for spectral sample.]
> 
> 4 - Save everything in a tensor of the appropriate size.
> 
> 5 - Give it as input to the DeepSense framework.
> 
> Could you please tell me if my approach is correct(especially in the third step)?

hi，did you try your method in the real world?Did it work?

**Comment by royanimal** [comment]
> I am also reading this paper and related codes. But I do not think it takes 10 random measurements from each time interval of length 0.25 seconds. The dimension of the input is **wide * inputFeature** **(20 * 120)** in the code. the wide is 20 as described in your step 2 , and the inputFeature is **sepcturalSamples * 6 * 2** as described in your step 3 **(10 * 6 * 2=120)**.

您好，看到您的回答，请问您说的这句话什么意思呢“But I do not think it takes 10 random measurements from each time interval of length 0.25 seconds”。
我的理解就是在0.25s内进行fft变换插值，因为原始的0.25s内可能没有这么多值，这个0.25s内的数据就从离散变成了连续的值，这样就可以提取10个随机的点。

**Comment by crocodilegogogo** [comment]
> 
> 
> > I am also reading this paper and related codes. But I do not think it takes 10 random measurements from each time interval of length 0.25 seconds. The dimension of the input is **wide * inputFeature** **(20 * 120)** in the code. the wide is 20 as described in your step 2 , and the inputFeature is **sepcturalSamples * 6 * 2** as described in your step 3 **(10 * 6 * 2=120)**.
> 
> 您好，看到您的回答，请问您说的这句话什么意思呢“But I do not think it takes 10 random measurements from each time interval of length 0.25 seconds”。
> 我的理解就是在0.25s内进行fft变换插值，因为原始的0.25s内可能没有这么多值，这个0.25s内的数据就从离散变成了连续的值，这样就可以提取10个随机的点。

感觉作者就是瞎写的，fft根本就不是按照短时傅里叶那样做的，20个fft很多都是补零补出来的，整个预处理过程看不出很强的逻辑；GRU一个做时间关联的，结果代码中构建的是卷积网络通道之间的关联。。。这种代码给了还不如不给，也很怀疑文章的真实性。作者团队虽然发了一系列的高水平文章，但是都不敢公开代码，所以很怀疑该团队工作的真实性。这样，很快就会臭了吧。

**Comment by yscacaca** [comment]
Since I saw some abusive comments, I would like to give my intuition on these pre-processing steps. The major reason for interpolation is due to the practical issues in sensor readings. Although we can split the time series into 0.25-second intervals, the original sensor measurements in these intervals are not uniformly sampled (which is the prerequisite of FFT). Therefore, we have to interpolate the original sensing readings in order to generate a uniformly sampled time series. Here, I choose linear interpolation, which can introduce small artifacts. But it works in practice. (Btw, you can choose other interpolation methods or apply non-uniform Fourier transform)
